---
- name: Cleaning up apt cache
  hosts: all
  become: yes # to use sudo
  become_user: root  
  tasks:
    - name: Stop and remove portainer container
      ansible.builtin.shell: docker stop portainer
      ansible.builtin.shell: docker rm portainer
    - name: Pull and run last portainer image
      ansible.builtin.shell: sudo docker run -d -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:2.22.0
        msg: "Pulling and bulding a new container with laterst portainer image"