---
- name: Redeploy portainer-ce latest
  hosts: all
  become: true
  become_method: sudo
  become_user: root

    - name: Deploy portainer
      community.docker.docker_container:
        name: portainer
        image: "docker.io/portainer/portainer-ce:2.22.0"
        ports:
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
        restart_policy: unless-stopped