---
- name: Redeploy portainer-ce latest
  hosts: all
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: Stop and remove the Portainer container if it exists
      community.docker.docker_container:
        name: portainer       # The name of the Portainer container
        state: absent         # Ensure the container is removed
      ignore_errors: yes      # Ignore errors if the container doesn't exist

    - name: Deploy portainer
      community.docker.docker_container:
        name: portainer
        image: "docker.io/portainer/portainer-ce:2.22.0"
        ports:
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
        restart_policy: unless-stopped
