---
- name: Add the user 'ansible' with a bash shell, appending the group 'root' and 'sudoers'
  hosts: all
  become: yes
  tasks:
  - name: Create user
    ansible.builtin.user:
      user: 
       name: ansible
       shell: /bin/bash
       groups: sudoers,root
       append: yes
       expires: -1
       password: "v6HVqFumarsF5x"
       create_home: yes