---
- name: Add the user 'ansible' with a bash shell, appending the group 'root' and 'sudoers'
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: Create user ansible
    user: 
       name: ansible
       shell: /bin/bash
       groups: root, adm, sudo
       append: yes
       expires: -1
#       password: "7920fc8765e57c4c5e5ea43ef1f16b0463bd4f27d9bb6ad505e637ede8605a56cba430098b32b0d000972e26bcfce2ec3796ef83e7bc99ec45773265b4de4275"
# I Tried with a password, but it seems to be hashed, no clear text working for now. This will overwrite the previous pw value.
       create_home: true
  - name: Set authorized key taken from file
    authorized_key:
     user: ansible
     state: present
     key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIh1qaMlD6A/4MnY0fw5VaMxExkzoqJyTENHG9ImGJCo semaphore01
