---
- hosts: all
  gather_facts: False
  tasks:
    - name: Check Dist Version
      shell: cat /etc/os-release
      shell: stat -c %w /
      register: response

    - debug: msg="{{ response.stdout }}"