---
- name: Set Belgrade TimeZone
  hosts: all
  become: true
  become_method: sudo
  become_user: root
    tasks:
    - name: Set Belgrade TimeZone
      timezone:
        name: Europe/Belgrade
