---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    time_zone: Europe/Belgrade
  tasks:
    - name: Set timezone to {{ time_zone }}
      community.general.timezone:
        name: "{{ time_zone }}"
