---
- name: Install list of apt packages
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Install a list of packages
      ansible.builtin.yum:
        name:
          - iotop
          - btop
          - sysstat
          - nano
          - iftop 
          - net-tools
          - traceroute
          - qemu-guest-agent
        state: present
    - name: Start qemu-guest-agent
      ansible.builtin.shell: sudo systemctl start qemu-guest-agent
    - name: Enable qemu-guest-agent
      ansible.builtin.shell: sudo systemctl enable qemu-guest-agent  