---
- name: Install qemu-guest-agent package
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  tasks:
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
    - name: Start guest qemu-guest-agent
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
        enabled: true    