---
- name: Clean node
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:

  - name: Remove kubadm config
    ansible.builtin.shell: sudo kubeadm reset

  - name: Remove kube packages
    ansible.builtin.shell: sudo apt remove kubeadm kubectl kubelet kubernetes-cni kube*

  - name: APT autoremove dependencies
    ansible.biltin.shell: sudo apt autoremove  

  - name: Remove kube home directory
    ansible.biltin.shell: sudo rm -rf ~/.kube