---
- name: Clean node
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:

#  - name: Remove kubadm config
#    ansible.builtin.shell: sudo kubeadm reset
# Need to add auto confirmation for "yes" as appears question "Are you sure you want to proceed? [y/N]:"

  - name: Remove kube packages
    ansible.builtin.shell: sudo apt remove kubeadm kubectl kubelet kubernetes-cni kube*

  - name: APT autoremove dependencies
    ansible.builtin.shell: sudo apt autoremove  

  - name: Remove kube home directory
    ansible.builtin.shell: sudo rm -rf ~/.kube

  - name: Remove Keyrings Directory (if it exists)
    ansible.builtin.shell: rm -rf /etc/apt/keyrings

  - name: Remove Existing Kubernetes Directory (if it exists)
    ansible.builtin.shell: sudo rm -rf /etc/apt/sources.list.d/pkgs_k8s_io_core_stable_v*