---
- name: Check installed apts
  hosts: all
  become: yes # to use sudo
  become_user: root  
  tasks:
    - name: Check installed apts
      ansible.builtin.shell: sudo apt list --installed
      register: response
    - debug: msg="{{ response.stdout }}"
