---
- name: Disable systemd-networkd-wait-online.service
  hosts: all
  become: yes  # to use sudo
  tasks:
    - name: Disable systemd-networkd-wait-online.service
      ansible.builtin.command:
        cmd: "systemctl disable systemd-networkd-wait-online.service"
      register: disable_service
      changed_when: "'disabled' in disable_service.stdout or 'disabled' in disable_service.stderr"

    - name: Verify the service is disabled
      ansible.builtin.systemd:
        name: systemd-networkd-wait-online.service
        enabled: no