---
- name: Reboot machine
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Ensure SELinux is disabled in config file
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
        state: present

    - name: Temporarily set SELinux to permissive mode
      command: setenforce 0
      when: ansible_selinux.status == "enabled"

    - name: Check if system reboot is required
      become: true
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Report if reboot is required
      ansible.builtin.debug:
        msg: "Reboot is required"
      when: reboot_required.stat.exists  