---
- name: Disable systemd-networkd-wait-online.service
  hosts: all
  become: yes # to use sudo
  become_user: root  
  tasks:
    - name: Check status systemd-networkd-wait-online.service
      ansible.builtin.shell: sudo systemctl status systemd-networkd-wait-online.service
     - name: Check status systemd-networkd-wait-online.service
      ansible.builtin.shell: sudo systemctl disable systemd-networkd-wait-online.service 