---
- name: Clone and run TDX script
  hosts: all
  become: true
  tasks:
    - name: Clone script
      ansible.builtin.shell: git clone -b noble-24.04 https://github.com/canonical/tdx.git
    - name: move into tdx directory
      ansible.builtin.shell: cd /home/ubuntu/tdx
    - name: Run installation
      ansible.builtin.shell: sudo ./setup-tdx-host.sh
 