---
- name: Update kernel on Ubuntu to 6.6.63
  hosts: all
  become: true
  become_method: sudo
  become_user: root


    - name: Update GRUB configuration to set default kernel
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_DEFAULT='
        line: 'GRUB_DEFAULT="Advanced options for Ubuntu>Ubuntu, with Linux 6.6.63-060663-generic"'

    - name: Update grub
      ansible.builtin.command: sudo update-grub 

    - name: Reboot the server
      ansible.builtin.reboot:
        msg: "Rebooting the server after waiting 100 seconds"
        connect_timeout: 5
        reboot_timeout: 250

    - name: Check kernel version after reboot
      ansible.builtin.command: uname -a
      register: kernel_info

    - name: Display kernel version output
      ansible.builtin.debug:
        msg: "Kernel version after reboot: {{ kernel_info.stdout }}"


