---
- name: Update kernel on Ubuntu to 6.6.50
  hosts: all
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: Download kernel
      ansible.builtin.shell: wget https://raw.githubusercontent.com/pimlie/ubuntu-mainline-kernel.sh/master/ubuntu-mainline-kernel.sh
    - name: Add +x
      ansible.builtin.shell: chmod +x ubuntu-mainline-kernel.sh
    - name: Move to bin
      ansible.builtin.shell: sudo mv ubuntu-mainline-kernel.sh /usr/local/bin/ 
    - name: Choose kernel version for install 
      ansible.builtin.shell: sudo ubuntu-mainline-kernel.sh -i 6.6.50
    - name: Wait for 100 seconds before rebooting
      ansible.builtin.pause:
        seconds: 100
    - name: Updated grub 
      ansible.builtin.shell: sudo update-grub
    - name: Reboot the server
      ansible.builtin.reboot:
        msg: "Rebooting the server after waiting 100 seconds"
        connect_timeout: 5
        reboot_timeout: 600

    - name: Check kernel version after reboot
      ansible.builtin.command: uname -a
      register: kernel_info

    - name: Display kernel version output
      ansible.builtin.debug:
        msg: "Kernel version after reboot: {{ kernel_info.stdout }}"

