---
- name: Update and upgrade apt packages
  hosts: all
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        update_cache: true

    - name: Update packages with yum
      when: ansible_pkg_mgr == 'yum'
      ansible.builtin.yum:
        name: '*'
        state: latest # noqa: package-latest

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        upgrade: dist

    - name: Upgrade packages with yum
      when: ansible_pkg_mgr == 'yum'
      ansible.builtin.yum:
        name: '*'
        state: latest # noqa: package-latest
        exclude: kernel*  

    - name: Log package updates
      shell: |
        echo "Update run on $(date)" >> /var/log/ansible_update.log
        if [ "{{ ansible_pkg_mgr }}" == "apt" ]; then
          apt list --upgradable >> /var/log/ansible_update.log
        elif [ "{{ ansible_pkg_mgr }}" == "yum" ]; then
          yum list updates >> /var/log/ansible_update.log
        fi
        args:
          executable: /bin/bash   
#         - name: Remove packages that were automatically installed to satisfy dependencies for other packages
#      ansible.builtin.shell: sudo apt-get -y autoremove    