---
- name: add-repo-nginx
  hosts: all
  become_user: root
  tasks:
    - name: Task 1
      yum:
        name: ppa:nginx/stable
        state: present
        enablerepo: ppa:nginx/stable
        disable_gpg_check: yes
        update_cache: yes
  
