# Add nginx stable repository from PPA and install its signing key.
# On Ubuntu target:
---
- name: Install list of apt packages
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - apt_repository:
      repo: ppa:nginx/stable