---
- name: Install list of apt packages
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
   - name: Install a list of packages
     apt:
       pkg:
       - software-properties-common
       - dialog apt-utils 
       - htop
       - iotop
       - iftop
       - nload
       - sysstat
       - net-tools
       - iputils-ping
       - traceroute
       - qemu-guest-agent
       autoclean: yes
       clean: yes

   - name: Start guest qemu-guest-agent
     ansible.builtin.service:
        name: qemu-guest-agent
        state: started
        enabled: true   