---
- name: Install list of apt packages
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
   - name: Fix broken packages
     ansible.builtin.shell: sudo apt --fix-broken install
   - name: Install a list of packages
     apt:
       pkg:
       - software-properties-common
       - nano
       - dialog 
       - apt-utils 
       - htop
       - iotop
       - iftop
       - nload
       - sysstat
       - net-tools
       - iputils-ping
       - traceroute
       - qemu-guest-agent
       - tmux
       autoclean: yes
       clean: yes
