---
- name: add-repo
  hosts: all
  tasks:
    - name: Task 1
      apt:
        name: ppa:nginx/stable
        state: present
        update_cache: yes
        force_apt_get: yes
        autoclean: yes
        autoremove: yes
  
