---
- name: Update and upgrade apt packages
  hosts: all
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: Update packages with apt
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade packages with apt
      apt: state=latest force_apt_get=yes


  
