---
- name: Update and upgrade apt packages
  hosts: all
  become: true
  become_method: sudo
  become_user: root

  tasks:
      - name: Update all host/vm packages
        ansible.builtin.apt:
          update_cache: true
          cache_valid_time: 3600
          name: "*"
          state: latest


  
