---
- name: Update and upgrade apt packages
  hosts: all
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: Update packages with apt
      ansible.builtin.apt:
      update_cache: true

  tasks:
    - name: Upgrade packages with apt
      ansible.builtin.apt:
      name: "*"
      state: latest


  
